// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbzxschlyevvyuvfplmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhienhzY2hseWV2dnl1dmZwbG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNzYxMDUsImV4cCI6MjA0ODY1MjEwNX0.0MrejaBuGDqVsx8blDx-b8Z7HzST0nIegvtRaYEFAo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);